# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Setup .NET9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Install Maui
      run: dotnet workload install maui
    - name: Install Wasm Tools .Net8
      run: dotnet workload install wasm-tools-net8
    - name: Install Wasm Tools .Net9
      run: dotnet workload install wasm-tools-net9
    - name: Build Maui Net8.0
      run: dotnet build ./Blazor-MAUI-Demos/Blazor_MAUI_Demos_NET8.csproj
    - name: Build Maui Net9.0
      run: dotnet build ./Blazor-MAUI-Demos/Blazor_MAUI_Demos_NET9.csproj
    - name: Build Server Net8.0
      run: dotnet build ./Blazor-Server-Demos/Blazor_Server_Demos_NET8.csproj
    - name: Build Server Net9.0
      run: dotnet build ./Blazor-Server-Demos/Blazor_Server_Demos_NET9.csproj
    - name: Build WebApp Net8.0
      run: dotnet build ./Blazor-WebApp-Demos/Blazor_WebApp_Demos/Blazor_WebApp_Demos.csproj
    - name: Build WebApp Net9.0
      run: dotnet build ./Blazor-WebApp-Demos/Blazor_WebApp_Demos/Blazor_WebApp_Demos_NET9.csproj
    - name: Build Wasm Net8.0
      run: dotnet build ./Blazor-WASM-Demos/Blazor_WASM_Demos_NET8.csproj
    - name: Build Wasm Net9.0
      run: dotnet build ./Blazor-WASM-Demos/Blazor_WASM_Demos_NET9.csproj

